# Generated by Django 3.1.2 on 2020-11-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
